### ISSUE TITLE
Internal Error when the transaction 

### ISSUE THREAD

**Issue by pvalette** [UNIRIS/uniris-node#19]
On blockchain.uniris.io, when I try to have details of an unknown transaction (or invalid format), the system returns an Internal Error instead of an user friendly error message.
Ex:  https://blockchain.uniris.io/explorer/transaction/sssssssss

On a local node, in debug mode, we have 

ArgumentError at GET /explorer/transaction/ssss
non-alphabet digit found: "s" (byte 115)

**Comment by pvalette** [comment]
Same type of issue but with a transaction is listed

To reproduce:
On Blockchain.uniris.io, filter by type=hosting, you should see one transaction '00DDFF1A2C5A9C1615499571EA31CCFA58DC5BEC318FF17562505884AB55F0848F', when you click to view the details, you have an internal error

**Comment by samuel-uniris** [comment]
Thanks for the issue.

I think fe353ae should fix it.

blockchain.uniris.io will be updated soon
