### ISSUE TITLE
Error message on http://localhost:4000/explorer/transactions

### ISSUE THREAD

**Issue by pvalette** [UNIRIS/uniris-node#21]
With a fresh installation based on the version available on 29/1/21

On the explorer  via http://localhost:4000/explorer/transactions
I received  a debug page with the follwing page

unhandled exit at GET /explorer/transactions
exited in: GenServer.call(#PID<0.670.0>, {:select, [pipe: [filter: #Function<11.114912407/1 in Uniris.DB.KeyValueImpl.list_transactions/1>, map: #Function<12.114912407/1 in Uniris.DB.KeyValueImpl.list_transactions/1>]]}, 5000) ** (EXIT) time out

**Comment by samuel-uniris** [comment]
It should have been fixed on 62933a11de738eab659e2d6650856a211b28662e.
