### ISSUE TITLE
"invalid smart contract" error

### ISSUE THREAD

**Issue by pvalette** [UNIRIS/uniris-node#24]
Via JS, when try to push a SC, with last version of SDK, the server return "invalid smart contract" error

Type of transaction is hosting and the code is define like this

 const code = `actions triggered by: transaction do
    set_type hosting
    set_content "Test SC" 
end `

**Comment by pvalette** [comment]
Tested with the lastest version from fresh installation

**Comment by samuel-uniris** [comment]
Hello. 

Thanks for the report, but I see one issue inside the smart code.
`triggered by` should be `triggered_by`.

Also please to consider to add authorized key and secret (= transaction seed) inside the transaction, otherwise nodes will not be able to recreate transaction on the contract chain.
