### ISSUE TITLE
Impossible de lancer run.sh

### ISSUE THREAD

**Issue by mibond** [UNIRIS/uniris-node#6]
Une fois run.sh lancé, il est indiqué que le logiciel n'est pas installé alors que c'est le cas.

**Comment by samuel-uniris** [comment]
Concernant cette erreur, cela est dû au fait que la release Erlang  n'a pas été déployée. Cette release est utilisé dans une but de production. 
Pour des phases de dev ou d'expérimentation vous pouvez utiliser  
`iex -S mix phx.server`

**Comment by mibond** [comment]
Merci, j'en profite pour vous demander 2 choses:

1. Pourquoi il est indiqué 2 Node? Il faut lancé les 2?
2. Je n'arrive pas a faire contacter deux serveurs distant mais deux pc en locale fonctionne, est-ce un problème réseau ou nominal?

**Comment by samuel-uniris** [comment]
2 noeuds est un exemple. Vous pouvez en lancez 2 , 3, 4 noeuds localement , aussi longtemps que le Crypto seed et le port P2P est différent .

Pour ce qui est des noeud distants nous n'avons pas encore implémenté le UPnP protocol permettant au noeuds derrière des box internets de communiquer ensemble.

**Comment by mibond** [comment]
En parlant du Crypto seed, si je le change, il y a une erreur au début et ca change le comportement du logiciel, super en tout cas. Une fois l'UPNP fonctionnel, on pourra rejoindre l'alpha net?

**Comment by samuel-uniris** [comment]
Il faut que le première noeud ai comme seed "node1" en mode dev

**Comment by samuel-uniris** [comment]
Concernant le fait de rejoindre le réseau Alpha , théoriquement oui. Après cela reste un réseau de test , donc risque de redémarrage et de suppression des données tant que la mise a chaud n'a pas été déployée.
