### ISSUE TITLE
Debian 9 et 10: Impossible d'exécuter install.sh

### ISSUE THREAD

**Issue by mibond** [UNIRIS/uniris-node#7]
Le programme s'arrête rapidement, a priori causé par NodePM (incompatibilité entre NPM et NODEJS)

./scripts/install_system_deps.sh: 6: ./scripts/install_system_deps.sh: function:                                                                                                                                                              not found
0000000000
./scripts/install_system_deps.sh: 8: ./scripts/install_system_deps.sh: Syntax er                                                                                                                                                             ror: "}" unexpected
./scripts/release.sh: 36: ./scripts/release.sh: mix: not found
./scripts/release.sh: 37: ./scripts/release.sh: mix: not found
./scripts/release.sh: 42: ./scripts/release.sh: mix: not found
./scripts/release.sh: 45: ./scripts/release.sh: npm: not found
grep: mix.exs: No such file or directory

Version:
Installation dir: INSTALL_DIR
./scripts/release.sh: 55: [: 0: unexpected operator
Generate release
./scripts/release.sh: 74: ./scripts/release.sh: mix: not found
Install MainNet release
Copy release into INSTALL_DIR/mainnet
cp: cannot stat '_build/prod/rel/uniris_node/releases//uniris_node.tar.gz': No s                                                                                                                                                             uch file or directory
tar (child): INSTALL_DIR/uniris_node.tar.gz: Cannot open: No such file or direct                                                                                                                                                             ory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Install TestNet release
Copy release into INSTALL_DIR/testnet
tar (child): INSTALL_DIR/uniris_node.tar.gz: Cannot open: No such file or direct                                                                                                                                                             ory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cp: cannot stat 'rel/test_runtime_config.exs': No such file or directory

**Comment by samuel-uniris** [comment]
Cela vient d'une erreur de compatibilité de bash. Le script a principalement été testé sur Ubuntu et Mac OS X. 

Nous allons travailler dessus pour une meilleure compatibilité. Merci du retour.

**Comment by samuel-uniris** [comment]
Après discussion avec l'équipe technique, nous allons supporter uniquement pour le moment Ubuntu 18.04 . La documentation sera mise a jour en ce sens. 

Merci de votre compréhension.
